name: Deploy React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t hs14/healthflow-reactjs \
          --build-arg REACT_APP_SERVER_BASE_URL=${{ secrets.REACT_APP_SERVER_BASE_URL }} .

      - name: Publish Image to Docker Hub
        run: docker push hs14/healthflow-reactjs:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull hs14/healthflow-reactjs:latest

      - name: Stop and Remove Existing Container
        run: |
          docker stop reactjs-app-container || true
          docker rm reactjs-app-container || true

      - name: Run Docker Container
        run: |
          docker run -d -p 5500:80\
           --name reactjs-app-container \
          hs14/healthflow-reactjs
