name: Deploying React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Installing Backend Dependencies
        run: npm install
        working-directory: ./BackEnd

      - name: Installing Frontend Dependencies
        run: npm install
        working-directory: ./FrontEnd

      - name: Building the Frontend Artifact
        run: npm run build
        working-directory: ./FrontEnd

      - name: Upload the Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-output
          path: ./BackEnd

      - name: Uploading the Frontend Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-output
          path: ./FrontEnd/dist

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Downloading Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-output

      - name: Downloading Frontend Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-output

      - name: Removing old Files
        run: sudo rm -rf /var/www/healthflow.harkirat.site/*

      - name: Moving the Files to serving directory
        run: sudo mv /home/ubuntu/healthflow/_work/HealthFlowWeb/HealthFlowWeb/* /var/www/healthflow.harkirat.site/

      - name: Setting ENVs from Github Secrets
        run: |
          sudo touch /var/www/healthflow.harkirat.site/.env && \
          echo "MONGO_URI=${{secrets.MONGO_URI}}" | sudo tee  -a /var/www/healthflow.harkirat.site/.env

      - name: Restart Backend
        run: |
          sudo systemctl daemon-reload && \
          sudo systemctl restart healthflow-backend && \
          sudo systemctl status healthflow-backend

      - name: Restart Frontend
        run: sudo systemctl restart nginx
