name: Deploying React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Installing Backend Dependencies
        run: |
          npm cache clean --force && \
          npm install
        working-directory: ./BackEnd

      - name: Installing Frontend Dependencies
        run: npm install
        working-directory: ./FrontEnd

      - name: Building the Frontend Artifact
        run: npm run build
        working-directory: ./FrontEnd

      - name: Installing Dashboard Dependencies
        run: npm install
        working-directory: ./DashBoard

      - name: Building the Dashboard Artifact
        run: npm run build
        working-directory: ./DashBoard

      - name: Upload the Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-output
          path: ./BackEnd

      - name: Uploading the Frontend Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-output
          path: ./FrontEnd/dist

      - name: Uploading the Dashboard Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-output
          path: ./DashBoard/dist

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Downloading Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-output

      - name: Downloading Frontend Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-output

      - name: Downloading Dashboard Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: dashboard-output
          path: /home/ubuntu/healthflow/_work/Dashboard

      - name: Removing old Files
        run: sudo rm -rf /var/www/healthflow.harkirat.site/*

      - name: Moving the Files to serving directory
        run: sudo mv /home/ubuntu/healthflow/_work/HealthFlowWeb/HealthFlowWeb/* /var/www/healthflow.harkirat.site/

      - name: Removing old Admin Files
        run: sudo rm -rf /var/www/dash-healthflow.harkirat.site/*

      - name: Moving the Files to serving directory
        run: sudo mv /home/ubuntu/healthflow/_work/Dashboard/* /var/www/dash-healthflow.harkirat.site/

      - name: Setting ENVs from Github Secrets
        run: |
          sudo touch /var/www/healthflow.harkirat.site/health.env && \
          echo "MONGO_URI=${{secrets.MONGO_URI}}" | sudo tee  -a /var/www/healthflow.harkirat.site/health.env
          echo "FRONTEND_URL=${{secrets.FRONTEND_URL}}" | sudo tee  -a /var/www/healthflow.harkirat.site/health.env
          echo "DASHBOARD_URL=${{secrets.DASHBOARD_URL}}" | sudo tee  -a /var/www/healthflow.harkirat.site/health.env
          echo "JWT_SECRET_KEY=${{secrets.JWT_SECRET_KEY}}" | sudo tee  -a /var/www/healthflow.harkirat.site/health.env
          echo "JWT_EXPIRES=${{secrets.JWT_EXPIRES}}" | sudo tee  -a /var/www/healthflow.harkirat.site/health.env
          echo "COOKIE_EXPIRE=${{secrets.COOKIE_EXPIRE}}" | sudo tee  -a /var/www/healthflow.harkirat.site/health.env
          echo "CLOUDINARY_CLOUD_NAME=${{secrets.CLOUDINARY_CLOUD_NAME}}" | sudo tee  -a /var/www/healthflow.harkirat.site/health.env
          echo "CLOUDINARY_API_SECRET=${{secrets.CLOUDINARY_API_SECRET}}" | sudo tee  -a /var/www/healthflow.harkirat.site/health.env
          echo "CLOUDINARY_API_KEY=${{secrets.CLOUDINARY_API_KEY}}" | sudo tee  -a /var/www/healthflow.harkirat.site/health.env

      - name: Restarting Node
        run: |
          sudo systemctl daemon-reload && \
          sudo systemctl restart healthflow-backend && \
          sudo systemctl status healthflow-backend

      - name: Restart Nginx
        run: sudo systemctl restart nginx
